### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by adammaj1** [dmackinnon1/r_examples#1]
Hi,

Thx for the code
Can you omake such image : 
https://commons.wikimedia.org/wiki/File:Dotswirl.gif
?

TIA
Adam

**Comment by dmackinnon1** [comment]
R would not be my first choice for this sort of animation. Some other examples of tools/languages you could use are mentioned [here](http://www.mathrecreation.com/2017/12/hello-phyllotaxis.html).

Using the **desmos calculator app**, you can create a version of that image, like the one [here](https://www.desmos.com/calculator/risuha09iw).  This one also grows as it swirls, but you could modify it to keep it at a fixed size (set b=200, for example).

Apparently there are packages that do support animated graphs in R. The package '**anim.plots**’ looks promising. If I have time, I may check it out and provide an update.

I also recently tried creating an image like this in d3js, over in the [d3jnotebook](https://github.com/dmackinnon1/d3jnotebook) repo. I was thinking about adding animation to that, similar to the desmos example above. Again, If I get around to it, I will provide an update.

**Comment by adammaj1** [comment]
Look great, thx. 
What I have to see your d3 examples not only as the src code ? 
Examples from https://d3js.org/ work .

**Comment by dmackinnon1** [comment]
The examples on the d3js.org page are specifically setup to display the html alongside the working example. That is not generally true of pages that use d3js (normally, you don't want to show source code). The d3js folks are very good at integrating source and display elements - they have even started up a new style of code notebook to do this called "observables" that takes this to the next level. See their beta of this here: https://beta.observablehq.com/

I don't currently have any examples in my d3 example repo that 'display the code at the same time as running the example,' but that would be a nice thing to try. Right now, I  have put a few of the examples on my github page, like [here ](https://dmackinnon1.github.io/phylo2.html) and also [here](https://dmackinnon1.github.io/bipartite2.html).

**Comment by dmackinnon1** [comment]
I've put an example for the original R question using the anim.plots library [here](https://github.com/dmackinnon1/r_examples/blob/master/simple/animated_phyllotaxis.r). Thanks for asking the question, it was good to learn a bit about anim.plots.
I do think that if your goal is to create this specific animation, there are nicer ways. I will maybe update the d3js example later on. Hope this  helps.
